default: &default
  adapter: postgresql
  encoding: utf8
  collation: sv_SE.UTF-8
  ctype: sv_SE.UTF-8
  template: template0
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['SHF_PROJECT_DATABASE_HOST'] %>  #host is needed for dockerization (database runs in a separate container) - testing

development:
  <<: *default
  database: shf_project_development

test: &test
  <<: *default
  database: shf_project_test

production:
  <<: *default
  database: shf_project_production
  username: shf_project
  password: <%= ENV['SHF_PROJECT_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test